slack:
  color: "#00afcc"

exclude:
  - "メモ"
  - "質問"

content:
  title: "Issueの振り返り"

  section1:
    title: "イシューの背景を理解する"
    image_url: "https://dol.ismcdn.jp/mwimgs/5/d/600/img_7e0b8adba77c91687a8078920dedc7be160077.jpg"

  section2:
    title: "目的と価値の明確化する"
    image_url: "https://news.walkerplus.com/article/1179677/12640174_615.jpg"

  section3:
    title: "このイシューで学んだ事"
    image_url: "https://dol.ismcdn.jp/mwimgs/8/d/500/img_8db0612c13c0013326bfb1b66431df95645897.jpg"